In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split
# from sklearn.impute import SimpleImputer
import xgboost as xgb
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [2]:
train = pd.read_csv('data/train.csv')
train = train.drop("id", axis=1)
train = train.drop('fac_7', axis=1)
test = pd.read_csv('data/test_data.csv')
train
# test

,fac_1,fac_2,fac_3,fac_4,fac_5,fac_6,fac_8,poi_1,poi_2,poi_3,size,price_monthly,room_count,total_call,gender
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1778.0,10038.0,4106.0,9.0000,1500000.0,6.0,72,campur
1,1.0,1.0,0.0,1.0,1.0,1.0,NaN,4548.0,9332.0,6867.0,12.0000,1500000.0,30.0,56,campur
2,1.0,NaN,1.0,1.0,1.0,1.0,1.0,5174.0,9021.0,3693.0,12.0000,1600000.0,20.0,109,campur
3,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1490.0,8954.0,2139.0,8.2500,1500000.0,15.0,54,campur
4,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1688.0,8851.0,2145.0,14.8500,2100000.0,10.0,19,campur
5,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1533.0,8715.0,3533.0,9.0000,1350000.0,7.0,5,putri
6,1.0,1.0,1.0,1.0,1.0,1.0,0.0,969.0,9079.0,2727.0,9.6250,1300000.0,20.0,20,putri
7,1.0,1.0,0.0,1.0,1.0,1.0,0.0,5200.0,8910.0,3762.0,10.5000,1000000.0,11.0,25,putri
8,1.0,1.0,1.0,1.0,1.0,1.0,0.0,4835.0,8490.0,3618.0,20.0000,4000000.0,8.0,4,putri
9,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2880.0,8698.0,2210.0,9.0000,1950000.0,25.0,24,campur
10,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3445.0,8635.0,2512.0,9.0000,1500000.0,21.0,12,putri
11,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2060.0,7997.0,3337.0,10.5000,1750000.0,34.0,19,putra
12,1.0,1.0,1.0,1.0,1.0,1.0,NaN,4582.0,6663.0,4400.0,12.2500,1350000.0,8.0,24,putri
13,1.0,1.0,0.0,1.0,1.0,1.0,0.0,3130.0,7416.0,3413.0,9.0000,2000000.0,13.0,12,putra
14,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3601.0,8465.0,2718.0,10.5000,1400000.0,40.0,24,putri
15,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2845.0,8760.0,2146.0,24.0000,2000000.0,45.0,9,campur
16,1.0,NaN,1.0,1.0,1.0,1.0,0.0,3855.0,6567.0,4260.0,12.0000,1800000.0,10.0,7,putri
17,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1490.0,8572.0,3184.0,12.0000,1500000.0,9.0,54,putra
18,1.0,1.0,1.0,NaN,1.0,1.0,0.0,3770.0,6291.0,4754.0,12.0000,1600000.0,25.0,15,putri
19,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2807.0,7496.0,3401.0,12.0000,1250000.0,16.0,26,putri
20,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1547.0,8563.0,3361.0,16.0000,2000000.0,15.0,7,putri
21,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1681.0,8481.0,3542.0,12.0000,1500000.0,8.0,14,putra
22,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1297.0,8772.0,2741.0,9.0000,NaN,30.0,31,putri
23,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2880.0,9899.0,1227.0,16.0000,1800000.0,26.0,57,campur
24,1.0,1.0,1.0,1.0,1.0,1.0,0.0,4220.0,9904.0,2399.0,16.0000,1800000.0,6.0,7,putri
25,1.0,1.0,1.0,NaN,1.0,1.0,1.0,2619.0,10326.0,688.0,16.0000,2250000.0,46.0,44,campur
26,1.0,1.0,1.0,1.0,1.0,1.0,0.0,3465.0,10139.0,1554.0,12.0000,2200000.0,27.0,13,campur
27,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1364.0,8744.0,3230.0,15.7500,1500000.0,12.0,10,putri
28,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1984.0,10632.0,358.0,12.0000,1500000.0,12.0,25,campur
29,1.0,1.0,1.0,1.0,1.0,0.0,0.0,3717.0,8869.0,2531.0,25.0000,1300000.0,20.0,35,putri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3263,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3629.0,11114.0,1326.0,9.0000,500000.0,5.0,51,putra
3264,0.0,0.0,0.0,1.0,NaN,0.0,0.0,3629.0,11114.0,1326.0,9.0000,600000.0,5.0,36,putra
3265,1.0,1.0,1.0,0.0,1.0,1.0,1.0,2210.0,11298.0,649.0,18.0000,3000000.0,1.0,16,putri
3266,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2401.0,8627.0,2200.0,25.0000,1000000.0,1.0,27,putra
3267,0.0,1.0,1.0,1.0,1.0,1.0,1.0,2401.0,NaN,2200.0,25.0000,1000000.0,1.0,60,putra
3268,0.0,0.0,0.0,1.0,1.0,0.0,0.0,723.0,9928.0,1708.0,12.0000,550000.0,10.0,18,putri
3269,0.0,1.0,0.0,1.0,1.0,0.0,0.0,727.0,9923.0,1708.0,12.0000,710000.0,10.0,23,putri
3270,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3879.0,13207.0,2387.0,9.0000,400000.0,7.0,82,campur
3271,0.0,1.0,0.0,1.0,1.0,1.0,1.0,4582.0,10620.0,2491.0,24.0000,1000000.0,7.0,9,putri
3272,0.0,0.0,0.0,0.0,1.0,0.0,1.0,4805.0,14521.0,5787.0,7.5000,525000.0,9.0,29,putri
3273,0.0,1.0,0.0,0.0,0.0,1.0,0.0,5679.0,10593.0,3666.0,24.0000,1000000.0,6.0,130,campur
3274,0.0,1.0,0.0,0.0,0.0,0.0,0.0,777.0,10651.0,2781.0,7.5000,600000.0,7.0,30,putra
3275,0.0,0.0,1.0,0.0,0.0,0.0,0.0,10406.0,660.0,11060.0,9.0000,500000.0,20.0,1,putra
3276,0.0,1.0,NaN,0.0,0.0,1.0,0.0,6202.0,6700.0,5531.0,12.0000,550000.0,8.0,31,putri
3277,0.0,0.0,1.0,0.0,0.0,0.0,1.0,6255.0,15604.0,7434.0,9.0000,350000.0,17.0,21,putra
3278,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1938.0,8110.0,3378.0,12.0000,500000.0,16.0,111,putri
3279,0.0,1.0,1.0,1.0,1.0,1.0,1.0,2036.0,8015.0,NaN,12.0000,500000.0,6.0,86,putri
3280,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1877.0,8569.0,2408.0,12.1500,1200000.0,5.0,9,putri
3281,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1879.0,8564.0,2412.0,18.0000,1500000.0,NaN,6,putri
3282,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1883.0,8562.0,2415.0,20.0000,1800000.0,5.0,4,putri
3283,0.0,0.0,1.0,1.0,1.0,0.0,1.0,4120.0,13706.0,2942.0,6.0000,500000.0,5.0,74,putri
3284,0.0,0.0,1.0,0.0,0.0,1.0,1.0,9238.0,819.0,10009.0,16.0000,500000.0,7.0,2,putra
3285,0.0,1.0,0.0,1.0,1.0,1.0,1.0,5425.0,15453.0,5138.0,20.0000,850000.0,8.0,28,putri
3286,0.0,0.0,0.0,1.0,1.0,0.0,1.0,3605.0,7681.0,NaN,9.0000,650000.0,6.0,6,putra
3287,NaN,1.0,0.0,1.0,1.0,0.0,1.0,3605.0,7681.0,NaN,12.0000,700000.0,16.0,24,putra
3288,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3393.0,6930.0,3921.0,10.5000,1600000.0,11.0,21,putri
3289,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3393.0,6930.0,3921.0,18.9600,2200000.0,2.0,1,putri
3290,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3393.0,6930.0,3921.0,21.2000,2500000.0,1.0,18,campur
3291,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1669.0,10065.0,3994.0,10.5625,400000.0,21.0,181,putri
3292,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2634.0,8854.0,2007.0,9.0000,450000.0,10.0,6,putra

In [3]:
# train = train.interpolate()
# train = train.dropna()
train = train.fillna(train.mean())
# imp = SimpleImputer()
# imp.fit(train)
# train_data_noNAN = imp.transform(train_data)
# train = imp.fit_transform(values)
# train = train.reset_index(drop=True)
# train

In [4]:
dictionaries = {'putri': -1, 'putra': 1, 'campur': 0}
df_gender = train['gender']
# df_gender
# dictionaries['putri']

In [5]:
number = []
for i in df_gender:
    
    numbered = dictionaries[i]
    number.append(numbered)
# number

In [6]:
dict_data = {'gender': number}
df_gender = pd.DataFrame.from_dict(dict_data)
df_gender

      gender
0          0
1          0
2          0
3          0
4          0
5         -1
6         -1
7         -1
8         -1
9          0
10        -1
11         1
12        -1
13         1
14        -1
15         0
16        -1
17         1
18        -1
19        -1
20        -1
21         1
22        -1
23         0
24        -1
25         0
26         0
27        -1
28         0
29        -1
...      ...
3263       1
3264       1
3265      -1
3266       1
3267       1
3268      -1
3269      -1
3270       0
3271      -1
3272      -1
3273       0
3274       1
3275       1
3276      -1
3277       1
3278      -1
3279      -1
3280      -1
3281      -1
3282      -1
3283      -1
3284       1
3285      -1
3286       1
3287       1
3288      -1
3289      -1
3290       0
3291      -1
3292       1

[3293 rows x 1 columns]

In [7]:
train['gender'] = df_gender['gender']
# train = train.drop('gender', axis=1)
# train = pd.concat([train, df_gender])
# train = train.reset_index()
# train = train.drop('index', axis=1)
# imp = SimpleImputer()
# imp.fit(train)
# train = imp.transform(train)
train

,fac_1,fac_2,fac_3,fac_4,fac_5,fac_6,fac_8,poi_1,poi_2,poi_3,size,price_monthly,room_count,total_call,gender
0,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1778.0,10038.000000,4106.000000,9.0000,1.500000e+06,6.00000,72,0
1,1.00000,1.000000,0.000000,1.000000,1.000000,1.0,0.51845,4548.0,9332.000000,6867.000000,12.0000,1.500000e+06,30.00000,56,0
2,1.00000,0.608263,1.000000,1.000000,1.000000,1.0,1.00000,5174.0,9021.000000,3693.000000,12.0000,1.600000e+06,20.00000,109,0
3,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,1490.0,8954.000000,2139.000000,8.2500,1.500000e+06,15.00000,54,0
4,1.00000,1.000000,0.000000,1.000000,1.000000,1.0,1.00000,1688.0,8851.000000,2145.000000,14.8500,2.100000e+06,10.00000,19,0
5,1.00000,1.000000,0.000000,1.000000,1.000000,0.0,0.00000,1533.0,8715.000000,3533.000000,9.0000,1.350000e+06,7.00000,5,-1
6,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,969.0,9079.000000,2727.000000,9.6250,1.300000e+06,20.00000,20,-1
7,1.00000,1.000000,0.000000,1.000000,1.000000,1.0,0.00000,5200.0,8910.000000,3762.000000,10.5000,1.000000e+06,11.00000,25,-1
8,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,4835.0,8490.000000,3618.000000,20.0000,4.000000e+06,8.00000,4,-1
9,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,2880.0,8698.000000,2210.000000,9.0000,1.950000e+06,25.00000,24,0
10,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,3445.0,8635.000000,2512.000000,9.0000,1.500000e+06,21.00000,12,-1
11,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,2060.0,7997.000000,3337.000000,10.5000,1.750000e+06,34.00000,19,1
12,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.51845,4582.0,6663.000000,4400.000000,12.2500,1.350000e+06,8.00000,24,-1
13,1.00000,1.000000,0.000000,1.000000,1.000000,1.0,0.00000,3130.0,7416.000000,3413.000000,9.0000,2.000000e+06,13.00000,12,1
14,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,3601.0,8465.000000,2718.000000,10.5000,1.400000e+06,40.00000,24,-1
15,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,2845.0,8760.000000,2146.000000,24.0000,2.000000e+06,45.00000,9,0
16,1.00000,0.608263,1.000000,1.000000,1.000000,1.0,0.00000,3855.0,6567.000000,4260.000000,12.0000,1.800000e+06,10.00000,7,-1
17,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1490.0,8572.000000,3184.000000,12.0000,1.500000e+06,9.00000,54,1
18,1.00000,1.000000,1.000000,0.562384,1.000000,1.0,0.00000,3770.0,6291.000000,4754.000000,12.0000,1.600000e+06,25.00000,15,-1
19,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,2807.0,7496.000000,3401.000000,12.0000,1.250000e+06,16.00000,26,-1
20,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1547.0,8563.000000,3361.000000,16.0000,2.000000e+06,15.00000,7,-1
21,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,1681.0,8481.000000,3542.000000,12.0000,1.500000e+06,8.00000,14,1
22,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,1297.0,8772.000000,2741.000000,9.0000,8.975029e+05,30.00000,31,-1
23,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,2880.0,9899.000000,1227.000000,16.0000,1.800000e+06,26.00000,57,0
24,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,4220.0,9904.000000,2399.000000,16.0000,1.800000e+06,6.00000,7,-1
25,1.00000,1.000000,1.000000,0.562384,1.000000,1.0,1.00000,2619.0,10326.000000,688.000000,16.0000,2.250000e+06,46.00000,44,0
26,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,3465.0,10139.000000,1554.000000,12.0000,2.200000e+06,27.00000,13,0
27,1.00000,1.000000,0.000000,1.000000,1.000000,0.0,0.00000,1364.0,8744.000000,3230.000000,15.7500,1.500000e+06,12.00000,10,-1
28,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1984.0,10632.000000,358.000000,12.0000,1.500000e+06,12.00000,25,0
29,1.00000,1.000000,1.000000,1.000000,1.000000,0.0,0.00000,3717.0,8869.000000,2531.000000,25.0000,1.300000e+06,20.00000,35,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3263,0.00000,0.000000,0.000000,0.000000,1.000000,0.0,0.00000,3629.0,11114.000000,1326.000000,9.0000,5.000000e+05,5.00000,51,1
3264,0.00000,0.000000,0.000000,1.000000,0.641416,0.0,0.00000,3629.0,11114.000000,1326.000000,9.0000,6.000000e+05,5.00000,36,1
3265,1.00000,1.000000,1.000000,0.000000,1.000000,1.0,1.00000,2210.0,11298.000000,649.000000,18.0000,3.000000e+06,1.00000,16,-1
3266,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,2401.0,8627.000000,2200.000000,25.0000,1.000000e+06,1.00000,27,1
3267,0.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,2401.0,9920.515189,2200.000000,25.0000,1.000000e+06,1.00000,60,1
3268,0.00000,0.000000,0.000000,1.000000,1.000000,0.0,0.00000,723.0,9928.000000,1708.000000,12.0000,5.500000e+05,10.00000,18,-1
3269,0.00000,1.000000,0.000000,1.000000,1.000000,0.0,0.00000,727.0,9923.000000,1708.000000,12.0000,7.100000e+05,10.00000,23,-1
3270,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,3879.0,13207.000000,2387.000000,9.0000,4.000000e+05,7.00000,82,0
3271,0.00000,1.000000,0.000000,1.000000,1.000000,1.0,1.00000,4582.0,10620.000000,2491.000000,24.0000,1.000000e+06,7.00000,9,-1
3272,0.00000,0.000000,0.000000,0.000000,1.000000,0.0,1.00000,4805.0,14521.000000,5787.000000,7.5000,5.250000e+05,9.00000,29,-1
3273,0.00000,1.000000,0.000000,0.000000,0.000000,1.0,0.00000,5679.0,10593.000000,3666.000000,24.0000,1.000000e+06,6.00000,130,0
3274,0.00000,1.000000,0.000000,0.000000,0.000000,0.0,0.00000,777.0,10651.000000,2781.000000,7.5000,6.000000e+05,7.00000,30,1
3275,0.00000,0.000000,1.000000,0.000000,0.000000,0.0,0.00000,10406.0,660.000000,11060.000000,9.0000,5.000000e+05,20.00000,1,1
3276,0.00000,1.000000,0.456515,0.000000,0.000000,1.0,0.00000,6202.0,6700.000000,5531.000000,12.0000,5.500000e+05,8.00000,31,-1
3277,0.00000,0.000000,1.000000,0.000000,0.000000,0.0,1.00000,6255.0,15604.000000,7434.000000,9.0000,3.500000e+05,17.00000,21,1
3278,0.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1938.0,8110.000000,3378.000000,12.0000,5.000000e+05,16.00000,111,-1
3279,0.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,2036.0,8015.000000,4906.215778,12.0000,5.000000e+05,6.00000,86,-1
3280,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1877.0,8569.000000,2408.000000,12.1500,1.200000e+06,5.00000,9,-1
3281,0.26161,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1879.0,8564.000000,2412.000000,18.0000,1.500000e+06,10.50605,6,-1
3282,1.00000,0.000000,1.000000,1.000000,1.000000,1.0,1.00000,1883.0,8562.000000,2415.000000,20.0000,1.800000e+06,5.00000,4,-1
3283,0.00000,0.000000,1.000000,1.000000,1.000000,0.0,1.00000,4120.0,13706.000000,2942.000000,6.0000,5.000000e+05,5.00000,74,-1
3284,0.00000,0.000000,1.000000,0.000000,0.000000,1.0,1.00000,9238.0,819.000000,10009.000000,16.0000,5.000000e+05,7.00000,2,1
3285,0.00000,1.000000,0.000000,1.000000,1.000000,1.0,1.00000,5425.0,15453.000000,5138.000000,20.0000,8.500000e+05,8.00000,28,-1
3286,0.00000,0.000000,0.000000,1.000000,1.000000,0.0,1.00000,3605.0,7681.000000,4906.215778,9.0000,6.500000e+05,6.00000,6,1
3287,0.26161,1.000000,0.000000,1.000000,1.000000,0.0,1.00000,3605.0,7681.000000,4906.215778,12.0000,7.000000e+05,16.00000,24,1
3288,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,3393.0,6930.000000,3921.000000,10.5000,1.600000e+06,11.00000,21,-1
3289,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,3393.0,6930.000000,3921.000000,18.9600,2.200000e+06,2.00000,1,-1
3290,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,3393.0,6930.000000,3921.000000,21.2000,2.500000e+06,1.00000,18,0
3291,0.00000,0.000000,1.000000,0.000000,1.000000,0.0,0.00000,1669.0,10065.000000,3994.000000,10.5625,4.000000e+05,21.00000,181,-1
3292,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,1.00000,2634.0,8854.000000,2007.000000,9.0000,4.500000e+05,10.00000,6,1

In [8]:
# train.corr()
# train.describe()

In [9]:
test_id = test['id']
test = test.drop("id", axis=1)
test = test.drop("fac_7", axis=1)
# test_id
test

,fac_1,fac_2,fac_3,fac_4,fac_5,fac_6,fac_8,poi_1,poi_2,poi_3,size,price_monthly,room_count,total_call
0,0,1,0,0,0,0,1,2634,8854,2007,21.00,700000,1,2
1,1,1,1,1,1,1,1,6569,3512,7341,12.00,1200000,16,30
2,0,1,1,1,1,0,1,10623,883,11250,12.00,700000,8,5
3,0,1,1,1,1,0,1,10592,876,11216,12.00,700000,16,6
4,0,1,0,0,1,0,1,1623,10204,3931,13.60,700000,6,39
5,1,1,1,1,1,1,1,7455,17049,8306,12.00,1600000,8,27
6,1,1,1,1,1,1,1,2318,7762,3852,9.00,1300000,11,208
7,0,1,0,1,1,0,0,3555,8229,5740,9.00,600000,10,50
8,1,1,1,1,1,0,1,3248,8243,2709,9.00,1800000,39,207
9,1,1,1,1,1,1,0,1320,8865,2447,12.00,1550000,7,92
10,0,0,1,1,1,1,1,9838,533,10724,12.00,400000,4,11
11,1,1,1,1,1,0,1,9919,306,10758,16.00,1500000,12,14
12,0,0,1,1,1,1,1,1881,8568,2407,12.15,800000,5,3
13,1,1,1,1,1,1,1,1549,8531,2861,13.50,2850000,3,49
14,0,0,0,1,0,1,1,6483,12758,8694,12.00,430000,6,15
15,0,1,1,0,0,1,1,8233,17663,9185,12.00,500000,10,18
16,0,1,0,0,0,0,0,9782,615,10447,12.00,650000,100,4
17,0,0,0,1,1,1,1,8787,2689,10092,20.00,350000,7,106
18,1,0,1,1,1,0,0,3443,13474,3932,9.00,1500000,1,46
19,1,1,1,1,1,1,0,5620,5341,7250,13.00,1250000,5,89
20,1,1,1,1,1,1,1,1883,8570,2403,14.00,1600000,1,19
21,0,1,1,1,1,1,1,7245,16638,8299,9.00,500000,15,79
22,0,0,0,0,0,0,0,7172,16728,8084,8.25,400000,7,9
23,0,1,1,0,0,0,1,7478,17274,8082,8.70,550000,5,4
24,1,1,1,1,1,0,0,815,10475,2988,12.00,1250000,10,10
25,0,0,0,0,1,1,0,6786,16175,7882,7.50,400000,30,18
26,0,0,0,0,0,0,1,5152,5018,5822,7.50,325000,15,39
27,0,1,1,1,1,1,0,3373,8516,2558,9.00,850000,6,163
28,0,0,0,0,1,0,0,9469,979,10088,9.00,300000,5,14
29,0,0,0,0,0,1,1,2801,7248,3997,9.00,400000,8,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,1,1,1,1,1,1,0,5164,7017,4574,10.50,1500000,10,1
795,0,1,1,0,0,1,1,4985,14857,5701,16.00,900000,20,10
796,0,0,0,0,1,1,1,2713,9429,5040,9.00,500000,8,11
797,0,1,1,1,1,1,0,9283,1163,9886,12.00,750000,19,7
798,0,0,1,0,1,0,1,2418,11474,4410,9.00,480000,7,10
799,0,0,0,1,1,0,1,2041,10400,454,9.00,600000,8,8
800,0,0,1,1,1,0,1,5152,8826,3753,12.00,500000,3,20
801,0,0,0,0,0,0,1,2950,7679,4881,7.50,350000,17,7
802,1,0,1,0,0,1,0,3880,6907,3956,9.00,650000,3,10
803,1,0,1,1,1,1,1,1136,8913,2855,12.00,1200000,4,11
804,0,0,0,0,0,0,0,5425,9806,3645,9.00,350000,2,3
805,0,0,0,1,1,0,0,3190,8569,2432,12.00,550000,25,10
806,0,1,0,0,0,0,1,2382,10372,501,15.00,750000,9,2
807,0,1,0,1,1,0,0,4818,12555,6890,12.00,700000,3,1
808,0,0,1,1,1,1,0,9467,1563,9937,12.00,550000,19,7
809,0,1,0,0,0,0,1,3587,9566,5919,9.00,650000,17,3
810,0,0,0,0,0,0,1,6665,9664,4971,9.00,1100000,2,4
811,0,1,1,0,0,0,0,4031,8047,3246,7.50,750000,20,3
812,0,0,0,1,1,0,1,4881,5806,5090,12.00,400000,5,1
813,1,1,0,1,1,1,1,1608,11442,3237,12.00,1500000,2,12
814,0,0,0,0,0,1,0,26572,34520,27837,9.00,1300000,2,4
815,0,0,1,0,0,0,0,6122,4040,6788,9.00,500000,2,4
816,1,1,1,1,1,1,0,9847,963,10426,20.00,1650000,10,5
817,0,1,0,1,1,0,1,9309,19346,8901,15.00,550000,3,14
818,0,1,1,0,0,0,0,4676,13795,2986,12.00,650000,9,9
819,1,1,1,1,1,0,1,2630,7780,3097,36.00,3000000,17,1
820,0,0,1,1,1,0,0,3660,7006,3830,9.00,600000,9,2
821,0,0,1,1,1,1,1,4055,11131,1780,7.50,700000,1,1
822,0,0,0,1,1,0,1,6724,3959,7051,9.00,350000,6,5
823,0,0,0,0,1,0,1,12296,6408,11783,6.00,250000,2,5

In [10]:
# nona = pd.read_csv('no_na_train.csv')
# fill = pd.read_csv('fill_missing_predicted.csv')
# train = pd.concat([nona, fill],ignore_index=True)
# train = train.drop('fac_7', axis=1)
# train = nona.append(fill)
train_fitur=train.drop('gender',axis=1)
# train_fitur=train_fitur.drop('size',axis=1)
train_label = train['gender']
# train
# train_gender
# X_train, X_test, Y_train, Y_test = train_test_split(train_fitur, train_label)

In [11]:
# X_train, X_test, Y_train, Y_test = train_test_split(train_fitur, train_label)
# X_train.to_csv('xtrain.csv', index=False)
# Y_train.to_csv('ytrain.csv', index=False)
# xytest = pd.DataFrame([X_test, Y_test])
# xytest = xytest.transpose()
# xytest.to_csv('xytest.csv', index=False)

# XY_test = pd.read_csv('xytest.csv')
# XY_train = pd.read_csv('xytrain.csv')
# Y_train = XY_train['gender']
# X_train = XY_train.drop(columns="gender").drop(columns="size")

# Y_test = XY_test['gender']
# X_test = XY_test.drop(columns="gender").drop(columns="size")

# X_train.shape
# XY_test
# XY_train = X_train.assign(gender = Y_train)
# XY_test = X_test.assign(gender = Y_test)
# XY_train.to_csv('xytrain.csv', index=False)
# XY_test.to_csv('xytest.csv', index=False)
# len(X_train)
# Y_train

In [12]:
# dt = ExtraTreesClassifier(n_estimators = 1234)
# dt.fit(X_train,Y_train)
# dt.score(X_test, Y_test)
# rf.fit(train_fitur,train_label)

# predict = rf.predict(test)
# predict

In [13]:
# count=[]
# for i in range(5):    
#     rf = RandomForestClassifier(n_estimators = 3000)
#     rf.fit(X_train,Y_train)
#     count.append(rf.score(X_test, Y_test))
# count
# rf.fit(train_fitur,train_label)

# predict = rf.predict(test)
# predict

In [14]:
# count = []
# for i in range(5):
#     gb = GradientBoostingClassifier(n_estimators = 2900)
#     gb.fit(X_train,Y_train)
#     count.append(gb.score(X_test, Y_test))
# count
# y_pred = gnb.predict(X_test)
# metrics.accuracy_score(Y_test, y_pred)
# pred = pd.read_csv('seventh_submission_fillna_gradientboost.csv')
# gb.fit(train_fitur,train_label)
# predict = gb.predict(test)
# metrics.accuracy_score(predict, pred)
# predict

In [15]:
# coun = []
# for i in range(10):
gb = GradientBoostingClassifier(n_estimators = 2900)
# gb.fit(X_train,Y_train)
# coun.append(gb.score(X_test, Y_test))
# coun
# y_pred = gnb.predict(X_test)
# metrics.accuracy_score(Y_test, y_pred)
# pred = pd.read_csv('seventh_submission_fillna_gradientboost.csv')
gb.fit(train_fitur,train_label)
predict = gb.predict(test)
# metrics.accuracy_score(predict, pred)
predict

array([-1, -1, -1, -1,  1, -1, -1,  1,  0, -1,  1,  1, -1,  0, -1, -1, -1,
        1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1, -1, -1,  1, -1,
       -1,  0,  1, -1, -1, -1,  1, -1, -1,  0, -1, -1, -1, -1,  0, -1,  1,
       -1, -1,  1, -1, -1,  1, -1, -1,  0, -1,  1,  0, -1,  1, -1, -1,  1,
        1, -1, -1,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  0, -1, -1, -1,
       -1, -1, -1, -1,  0, -1, -1, -1, -1,  1, -1, -1,  1, -1,  1,  1, -1,
       -1,  1, -1, -1, -1, -1,  0,  1, -1,  1,  1,  1,  1,  0, -1, -1, -1,
        1, -1, -1,  0, -1, -1, -1, -1, -1,  0, -1, -1,  0, -1, -1, -1, -1,
       -1, -1, -1, -1,  1, -1, -1, -1,  1, -1, -1,  0, -1, -1,  1,  1, -1,
       -1,  0,  0,  0, -1,  0, -1, -1,  1,  1,  1,  0, -1,  0, -1, -1, -1,
        0, -1,  0, -1, -1, -1, -1, -1, -1,  0,  1, -1, -1,  1,  1, -1,  0,
        1, -1,  1, -1,  0, -1, -1, -1,  1, -1,  1, -1, -1,  1,  0, -1, -1,
        0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1,
        0, -1,  0,  1, -1,  0, -1,  1,  1,  1, -1,  1,  1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1,  0,  1,  1,
        0,  0,  1,  0, -1, -1, -1, -1,  1, -1, -1, -1, -1,  1,  0, -1, -1,
        1,  0,  1, -1, -1,  0, -1, -1,  1, -1, -1, -1, -1,  1,  0, -1,  1,
        1,  1,  1, -1, -1, -1,  1,  0, -1,  1, -1, -1, -1, -1,  0,  0, -1,
       -1, -1,  0,  0, -1,  1, -1,  1,  1,  1, -1,  1,  1, -1,  1,  0, -1,
        1,  0, -1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1,  0, -1,  0, -1,
        1, -1,  1,  1,  1, -1,  1,  1,  1,  0, -1,  1,  1, -1, -1, -1, -1,
       -1, -1,  1, -1,  0, -1,  0,  0, -1, -1, -1, -1,  1, -1,  1,  0,  1,
       -1, -1, -1, -1, -1, -1,  0,  0,  0, -1,  0,  0,  0,  1, -1,  1, -1,
       -1, -1, -1,  1, -1,  0,  0,  1, -1, -1,  1,  0,  1, -1, -1,  1, -1,
        0, -1,  0, -1, -1, -1, -1,  1,  1, -1, -1,  0, -1, -1, -1, -1,  0,
       -1,  0,  0, -1, -1, -1,  1,  1, -1,  0,  0,  0,  1, -1,  1,  0,  1,
       -1, -1,  1,  1,  1,  0,  0, -1, -1,  1,  0,  0, -1, -1,  0, -1, -1,
        0, -1,  1,  0,  1,  0,  0,  0, -1, -1, -1,  1,  0,  0,  1,  0, -1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1,  0,  0, -1, -1, -1, -1, -1, -1,
        0, -1,  1,  1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1,  0, -1, -1,
       -1,  1,  0,  0,  0,  1, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1,  1, -1, -1,  1, -1, -1, -1,  1, -1,  0, -1, -1,
        1,  1,  1,  1, -1,  1,  0, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,
        1,  0,  0,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1,
        1,  0,  0,  0, -1,  0, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1,
        0, -1, -1,  1, -1,  1,  1, -1, -1, -1,  1, -1, -1, -1, -1,  1,  1,
       -1, -1,  1, -1,  1,  1, -1, -1,  1,  1, -1,  0, -1, -1, -1, -1, -1,
       -1,  0, -1, -1,  1,  1, -1, -1, -1,  0, -1, -1,  0,  0,  1, -1,  1,
       -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1,  1,  1,
       -1, -1, -1,  0, -1, -1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1,  0,
       -1, -1, -1, -1,  1,  1, -1, -1,  1, -1,  0, -1, -1, -1,  1,  1,  1,
       -1,  0,  0,  1, -1,  1, -1,  1,  1,  1,  1,  0, -1, -1, -1,  1,  1,
        1,  1, -1, -1,  1, -1, -1, -1, -1, -1,  1,  1, -1,  0,  1, -1,  1,
        1, -1, -1,  1,  1,  1,  1,  0,  1, -1, -1, -1, -1, -1, -1, -1, -1,
        1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1,  1, -1, -1,
       -1,  1,  1, -1, -1,  1, -1, -1,  0,  0,  1, -1, -1, -1, -1, -1, -1,
        1, -1, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1,
       -1,  1,  1, -1, -1,  1, -1,  1, -1, -1, -1,  0, -1, -1,  1,  0,  1,
       -1,  1, -1, -1,  1, -1, -1,  0])

In [16]:
# ab = AdaBoostClassifier(n_estimators = 2000)
# ab.fit(X_train,Y_train)
# ab.score(X_test, Y_test)

In [17]:
# xg = xgb.XGBClassifier(n_estimators = 3000)
# xg.fit(X_train,Y_train)
# xg.score(X_test, Y_test)

In [18]:
# gnb = GaussianNB()
# gnb.fit(X_train,Y_train)
# gnb.score(X_test, Y_test)
# y_pred = gnb.predict(X_test)
# metrics.accuracy_score(Y_test, y_pred)

In [19]:
# type(test_id)
converter = {-1: 'putri', 0:'campur', 1:'putra'}

predict = [converter[x] for x in predict]
predict_series = pd.Series(data=predict, name='gender')
submission = pd.DataFrame([test_id, predict_series])
submission = submission.transpose()
# submission.to_csv('submission/12th_submission_gradientboost_regression.csv', index=False)
submission

AttributeError: 'numpy.ndarray' object has no attribute 'map'