In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

In [2]:
train = pd.read_csv('data/train.csv')
train = train.drop('id', axis=1)
train = train.drop('fac_7', axis=1)
train = train.fillna(train.mean())
train['gender']=train['gender'].map({'putri': 1, 'putra': 2, 'campur': 3})
test = pd.read_csv('data/test_data.csv')
len(train)

3293

In [3]:
train_fitur = train.drop('gender', axis=1)
train_fitur

,fac_1,fac_2,fac_3,fac_4,fac_5,fac_6,fac_8,poi_1,poi_2,poi_3,size,price_monthly,room_count,total_call
0,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1778.0,10038.000000,4106.000000,9.0000,1.500000e+06,6.00000,72
1,1.00000,1.000000,0.000000,1.000000,1.000000,1.0,0.51845,4548.0,9332.000000,6867.000000,12.0000,1.500000e+06,30.00000,56
2,1.00000,0.608263,1.000000,1.000000,1.000000,1.0,1.00000,5174.0,9021.000000,3693.000000,12.0000,1.600000e+06,20.00000,109
3,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,1490.0,8954.000000,2139.000000,8.2500,1.500000e+06,15.00000,54
4,1.00000,1.000000,0.000000,1.000000,1.000000,1.0,1.00000,1688.0,8851.000000,2145.000000,14.8500,2.100000e+06,10.00000,19
5,1.00000,1.000000,0.000000,1.000000,1.000000,0.0,0.00000,1533.0,8715.000000,3533.000000,9.0000,1.350000e+06,7.00000,5
6,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,969.0,9079.000000,2727.000000,9.6250,1.300000e+06,20.00000,20
7,1.00000,1.000000,0.000000,1.000000,1.000000,1.0,0.00000,5200.0,8910.000000,3762.000000,10.5000,1.000000e+06,11.00000,25
8,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,4835.0,8490.000000,3618.000000,20.0000,4.000000e+06,8.00000,4
9,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,2880.0,8698.000000,2210.000000,9.0000,1.950000e+06,25.00000,24
10,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,3445.0,8635.000000,2512.000000,9.0000,1.500000e+06,21.00000,12
11,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,2060.0,7997.000000,3337.000000,10.5000,1.750000e+06,34.00000,19
12,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.51845,4582.0,6663.000000,4400.000000,12.2500,1.350000e+06,8.00000,24
13,1.00000,1.000000,0.000000,1.000000,1.000000,1.0,0.00000,3130.0,7416.000000,3413.000000,9.0000,2.000000e+06,13.00000,12
14,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,3601.0,8465.000000,2718.000000,10.5000,1.400000e+06,40.00000,24
15,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,2845.0,8760.000000,2146.000000,24.0000,2.000000e+06,45.00000,9
16,1.00000,0.608263,1.000000,1.000000,1.000000,1.0,0.00000,3855.0,6567.000000,4260.000000,12.0000,1.800000e+06,10.00000,7
17,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1490.0,8572.000000,3184.000000,12.0000,1.500000e+06,9.00000,54
18,1.00000,1.000000,1.000000,0.562384,1.000000,1.0,0.00000,3770.0,6291.000000,4754.000000,12.0000,1.600000e+06,25.00000,15
19,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,2807.0,7496.000000,3401.000000,12.0000,1.250000e+06,16.00000,26
20,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1547.0,8563.000000,3361.000000,16.0000,2.000000e+06,15.00000,7
21,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,1681.0,8481.000000,3542.000000,12.0000,1.500000e+06,8.00000,14
22,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,1297.0,8772.000000,2741.000000,9.0000,8.975029e+05,30.00000,31
23,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,2880.0,9899.000000,1227.000000,16.0000,1.800000e+06,26.00000,57
24,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,4220.0,9904.000000,2399.000000,16.0000,1.800000e+06,6.00000,7
25,1.00000,1.000000,1.000000,0.562384,1.000000,1.0,1.00000,2619.0,10326.000000,688.000000,16.0000,2.250000e+06,46.00000,44
26,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,0.00000,3465.0,10139.000000,1554.000000,12.0000,2.200000e+06,27.00000,13
27,1.00000,1.000000,0.000000,1.000000,1.000000,0.0,0.00000,1364.0,8744.000000,3230.000000,15.7500,1.500000e+06,12.00000,10
28,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1984.0,10632.000000,358.000000,12.0000,1.500000e+06,12.00000,25
29,1.00000,1.000000,1.000000,1.000000,1.000000,0.0,0.00000,3717.0,8869.000000,2531.000000,25.0000,1.300000e+06,20.00000,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3263,0.00000,0.000000,0.000000,0.000000,1.000000,0.0,0.00000,3629.0,11114.000000,1326.000000,9.0000,5.000000e+05,5.00000,51
3264,0.00000,0.000000,0.000000,1.000000,0.641416,0.0,0.00000,3629.0,11114.000000,1326.000000,9.0000,6.000000e+05,5.00000,36
3265,1.00000,1.000000,1.000000,0.000000,1.000000,1.0,1.00000,2210.0,11298.000000,649.000000,18.0000,3.000000e+06,1.00000,16
3266,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,2401.0,8627.000000,2200.000000,25.0000,1.000000e+06,1.00000,27
3267,0.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,2401.0,9920.515189,2200.000000,25.0000,1.000000e+06,1.00000,60
3268,0.00000,0.000000,0.000000,1.000000,1.000000,0.0,0.00000,723.0,9928.000000,1708.000000,12.0000,5.500000e+05,10.00000,18
3269,0.00000,1.000000,0.000000,1.000000,1.000000,0.0,0.00000,727.0,9923.000000,1708.000000,12.0000,7.100000e+05,10.00000,23
3270,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,3879.0,13207.000000,2387.000000,9.0000,4.000000e+05,7.00000,82
3271,0.00000,1.000000,0.000000,1.000000,1.000000,1.0,1.00000,4582.0,10620.000000,2491.000000,24.0000,1.000000e+06,7.00000,9
3272,0.00000,0.000000,0.000000,0.000000,1.000000,0.0,1.00000,4805.0,14521.000000,5787.000000,7.5000,5.250000e+05,9.00000,29
3273,0.00000,1.000000,0.000000,0.000000,0.000000,1.0,0.00000,5679.0,10593.000000,3666.000000,24.0000,1.000000e+06,6.00000,130
3274,0.00000,1.000000,0.000000,0.000000,0.000000,0.0,0.00000,777.0,10651.000000,2781.000000,7.5000,6.000000e+05,7.00000,30
3275,0.00000,0.000000,1.000000,0.000000,0.000000,0.0,0.00000,10406.0,660.000000,11060.000000,9.0000,5.000000e+05,20.00000,1
3276,0.00000,1.000000,0.456515,0.000000,0.000000,1.0,0.00000,6202.0,6700.000000,5531.000000,12.0000,5.500000e+05,8.00000,31
3277,0.00000,0.000000,1.000000,0.000000,0.000000,0.0,1.00000,6255.0,15604.000000,7434.000000,9.0000,3.500000e+05,17.00000,21
3278,0.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1938.0,8110.000000,3378.000000,12.0000,5.000000e+05,16.00000,111
3279,0.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,2036.0,8015.000000,4906.215778,12.0000,5.000000e+05,6.00000,86
3280,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1877.0,8569.000000,2408.000000,12.1500,1.200000e+06,5.00000,9
3281,0.26161,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,1879.0,8564.000000,2412.000000,18.0000,1.500000e+06,10.50605,6
3282,1.00000,0.000000,1.000000,1.000000,1.000000,1.0,1.00000,1883.0,8562.000000,2415.000000,20.0000,1.800000e+06,5.00000,4
3283,0.00000,0.000000,1.000000,1.000000,1.000000,0.0,1.00000,4120.0,13706.000000,2942.000000,6.0000,5.000000e+05,5.00000,74
3284,0.00000,0.000000,1.000000,0.000000,0.000000,1.0,1.00000,9238.0,819.000000,10009.000000,16.0000,5.000000e+05,7.00000,2
3285,0.00000,1.000000,0.000000,1.000000,1.000000,1.0,1.00000,5425.0,15453.000000,5138.000000,20.0000,8.500000e+05,8.00000,28
3286,0.00000,0.000000,0.000000,1.000000,1.000000,0.0,1.00000,3605.0,7681.000000,4906.215778,9.0000,6.500000e+05,6.00000,6
3287,0.26161,1.000000,0.000000,1.000000,1.000000,0.0,1.00000,3605.0,7681.000000,4906.215778,12.0000,7.000000e+05,16.00000,24
3288,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,3393.0,6930.000000,3921.000000,10.5000,1.600000e+06,11.00000,21
3289,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,3393.0,6930.000000,3921.000000,18.9600,2.200000e+06,2.00000,1
3290,1.00000,1.000000,1.000000,1.000000,1.000000,1.0,1.00000,3393.0,6930.000000,3921.000000,21.2000,2.500000e+06,1.00000,18
3291,0.00000,0.000000,1.000000,0.000000,1.000000,0.0,0.00000,1669.0,10065.000000,3994.000000,10.5625,4.000000e+05,21.00000,181
3292,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,1.00000,2634.0,8854.000000,2007.000000,9.0000,4.500000e+05,10.00000,6

In [4]:
# dictionaries = {'putri': 1, 'putra': 2, 'campur': 3}
train_label = train['gender']
train_label

0       3
1       3
2       3
3       3
4       3
5       1
6       1
7       1
8       1
9       3
10      1
11      2
12      1
13      2
14      1
15      3
16      1
17      2
18      1
19      1
20      1
21      2
22      1
23      3
24      1
25      3
26      3
27      1
28      3
29      1
       ..
3263    2
3264    2
3265    1
3266    2
3267    2
3268    1
3269    1
3270    3
3271    1
3272    1
3273    3
3274    2
3275    2
3276    1
3277    2
3278    1
3279    1
3280    1
3281    1
3282    1
3283    1
3284    2
3285    1
3286    2
3287    2
3288    1
3289    1
3290    3
3291    1
3292    2
Name: gender, Length: 3293, dtype: int64

In [5]:
fac1 = tf.feature_column.numeric_column('fac_1')
fac2 = tf.feature_column.numeric_column('fac_2')
fac3 = tf.feature_column.numeric_column('fac_3')
fac4 = tf.feature_column.numeric_column('fac_4')
fac5 = tf.feature_column.numeric_column('fac_5')
fac6 = tf.feature_column.numeric_column('fac_6')
# fac7 = tf.feature_column.numeric_column('fac_7')
fac8 = tf.feature_column.numeric_column('fac_8')
poi1 = tf.feature_column.numeric_column('poi_1')
poi2 = tf.feature_column.numeric_column('poi_2')
poi3 = tf.feature_column.numeric_column('poi_3')
size = tf.feature_column.numeric_column('size')
price = tf.feature_column.numeric_column('price_monthly')
room = tf.feature_column.numeric_column('room_count')
call = tf.feature_column.numeric_column('total_call')

In [6]:
features = [fac1,fac2,fac3,fac4,fac5,fac6,fac8,poi1,poi2,poi3,size,price,room,call]

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(train_fitur, train_label, test_size=0.3, random_state=101)

In [18]:
model=tf.estimator.BoostedTreesClassifier(feature_columns=features,n_classes=4, n_batches_per_layer=100)

ValueError: For now only binary classification is supported.n_classes given as 4

In [11]:
input_func = tf.estimator.inputs.pandas_input_fn(x=train_fitur,y=train_label,batch_size=3293,num_epochs=1,shuffle=True)
model.train(input_fn=input_func, steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/q2/4s328tsn4tx7w0qztf69j7p40000gn/T/tmpc7hrovzp/model.ckpt.
INFO:tensorflow:loss = 188461090.0, step = 1
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/q2/4s328tsn4tx7w0qztf69j7p40000gn/T/tmpc7hrovzp/model.ckpt.
INFO:tensorflow:Loss for final step: 188461090.0.

In [ ]:
# eval_inpu_func = tf.estimator.inputs.pandas_input_fn(x=X_test,y=Y_test,batch_size=10,num_epochs=1000,shuffle=False)
# model.evaluate(eval_inpu_func, steps=1000)

In [14]:
pred = tf.estimator.inputs.pandas_input_fn(x=test, batch_size=824, num_epochs=1, shuffle=False)
prediction = model.predict(input_fn=pred)
final=[]
for i in prediction:
    final.append(i['class_ids'][0])
pd.DataFrame(final)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/q2/4s328tsn4tx7w0qztf69j7p40000gn/T/tmpc7hrovzp/model.ckpt-1
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

       0
0      3
1      3
2      3
3      3
4      3
5      3
6      3
7      3
8      3
9      3
10     3
11     3
12     3
13     3
14     3
15     3
16     3
17     3
18     3
19     3
20     3
21     3
22     3
23     3
24     3
25     3
26     3
27     3
28     3
29     3
...   ..
82370  3
82371  3
82372  3
82373  3
82374  3
82375  3
82376  3
82377  3
82378  3
82379  3
82380  3
82381  3
82382  3
82383  3
82384  3
82385  3
82386  3
82387  3
82388  3
82389  3
82390  3
82391  3
82392  3
82393  3
82394  3
82395  3
82396  3
82397  3
82398  3
82399  3

[82400 rows x 1 columns]